server:
  port: 8088

spring:
  application:
    name: demo
  profiles:
    active: local

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8

  data:
    redis:
      port: 6379
      host: localhost
      password: D5sdfsdvdrVdm_2021

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    lazy-loading-enabled: true
    aggressive-lazy-loading: false # true 积极加载，false 消极加载
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.example.dao.entity
  global-config:
    db-config:
      logic-delete-field: delFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#    lazy-load-trigger-methods:
